name: Create Release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

   # - name: Update version in YAML
   #   run: |
     #   sed -i 's/old_version/new_version/' path/to/file.yaml
        # Fügen Sie hier das Skript ein, um die Versionsnummer in Ihrer YAML-Datei zu aktualisieren
        # Beispiel: sed -i 's/old_version/new_version/' path/to/file.yaml

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Zip repository
      run: |
        zip -r custom-name-${{ github.ref }}.zip .
    
    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./custom-name-${{ github.ref }}.zip
        asset_name: custom-name-${{ github.ref }}.zip
        asset_content_type: application/zip
