name: Automatic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

   


    - name: Determine new version
      id: version
      run: |
        # Holen des neuesten Tags, das einem Semver-Muster entspricht
        LAST_VERSION=$(git tag -l --sort=-v:refname 'v*' | head -n 1 | sed 's/^v//')
        if [ -z "$LAST_VERSION" ]; then
          LAST_VERSION="0.0.0"
        fi
        echo "Letzte Version: $LAST_VERSION"
        # Inkrementieren der Patch-Version
        NEW_VERSION=$(echo $LAST_VERSION | awk -F. -v OFS=. '{$NF += 1; print}')
        echo "Neue Version: $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ env.NEW_VERSION }}

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'RescanSongsMod.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.NEW_VERSION }}
        name: Release ${{ env.NEW_VERSION }}
        body: ${{ steps.tag_version.outputs.changelog }}
        artifacts: 'RescanSongsMod.zip'

        
 
